// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zan.proto

package microservice.protoc.zan.grpc;

public final class Zan {
  private Zan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ModelZanCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ModelZanCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 收藏内容ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * APP内容类型
     * </pre>
     *
     * <code>int32 app_id = 2;</code>
     */
    int getAppId();

    /**
     * <pre>
     * APP内容ID
     * </pre>
     *
     * <code>int32 third_id = 3;</code>
     */
    int getThirdId();

    /**
     * <pre>
     * 真实点赞数
     * </pre>
     *
     * <code>int32 real_count = 4;</code>
     */
    int getRealCount();

    /**
     * <pre>
     * 展示点赞数
     * </pre>
     *
     * <code>int32 show_count = 5;</code>
     */
    int getShowCount();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int32 created_at = 6;</code>
     */
    int getCreatedAt();

    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>int32 updated_at = 7;</code>
     */
    int getUpdatedAt();
  }
  /**
   * Protobuf type {@code ModelZanCount}
   */
  public  static final class ModelZanCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ModelZanCount)
      ModelZanCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ModelZanCount.newBuilder() to construct.
    private ModelZanCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModelZanCount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ModelZanCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ModelZanCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              appId_ = input.readInt32();
              break;
            }
            case 24: {

              thirdId_ = input.readInt32();
              break;
            }
            case 32: {

              realCount_ = input.readInt32();
              break;
            }
            case 40: {

              showCount_ = input.readInt32();
              break;
            }
            case 48: {

              createdAt_ = input.readInt32();
              break;
            }
            case 56: {

              updatedAt_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return microservice.protoc.zan.grpc.Zan.internal_static_ModelZanCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return microservice.protoc.zan.grpc.Zan.internal_static_ModelZanCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              microservice.protoc.zan.grpc.Zan.ModelZanCount.class, microservice.protoc.zan.grpc.Zan.ModelZanCount.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 收藏内容ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int APP_ID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <pre>
     * APP内容类型
     * </pre>
     *
     * <code>int32 app_id = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int THIRD_ID_FIELD_NUMBER = 3;
    private int thirdId_;
    /**
     * <pre>
     * APP内容ID
     * </pre>
     *
     * <code>int32 third_id = 3;</code>
     */
    public int getThirdId() {
      return thirdId_;
    }

    public static final int REAL_COUNT_FIELD_NUMBER = 4;
    private int realCount_;
    /**
     * <pre>
     * 真实点赞数
     * </pre>
     *
     * <code>int32 real_count = 4;</code>
     */
    public int getRealCount() {
      return realCount_;
    }

    public static final int SHOW_COUNT_FIELD_NUMBER = 5;
    private int showCount_;
    /**
     * <pre>
     * 展示点赞数
     * </pre>
     *
     * <code>int32 show_count = 5;</code>
     */
    public int getShowCount() {
      return showCount_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 6;
    private int createdAt_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int32 created_at = 6;</code>
     */
    public int getCreatedAt() {
      return createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 7;
    private int updatedAt_;
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>int32 updated_at = 7;</code>
     */
    public int getUpdatedAt() {
      return updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (appId_ != 0) {
        output.writeInt32(2, appId_);
      }
      if (thirdId_ != 0) {
        output.writeInt32(3, thirdId_);
      }
      if (realCount_ != 0) {
        output.writeInt32(4, realCount_);
      }
      if (showCount_ != 0) {
        output.writeInt32(5, showCount_);
      }
      if (createdAt_ != 0) {
        output.writeInt32(6, createdAt_);
      }
      if (updatedAt_ != 0) {
        output.writeInt32(7, updatedAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (thirdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, thirdId_);
      }
      if (realCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, realCount_);
      }
      if (showCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, showCount_);
      }
      if (createdAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, createdAt_);
      }
      if (updatedAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, updatedAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof microservice.protoc.zan.grpc.Zan.ModelZanCount)) {
        return super.equals(obj);
      }
      microservice.protoc.zan.grpc.Zan.ModelZanCount other = (microservice.protoc.zan.grpc.Zan.ModelZanCount) obj;

      if (getId()
          != other.getId()) return false;
      if (getAppId()
          != other.getAppId()) return false;
      if (getThirdId()
          != other.getThirdId()) return false;
      if (getRealCount()
          != other.getRealCount()) return false;
      if (getShowCount()
          != other.getShowCount()) return false;
      if (getCreatedAt()
          != other.getCreatedAt()) return false;
      if (getUpdatedAt()
          != other.getUpdatedAt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + THIRD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getThirdId();
      hash = (37 * hash) + REAL_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRealCount();
      hash = (37 * hash) + SHOW_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getShowCount();
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt();
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZanCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(microservice.protoc.zan.grpc.Zan.ModelZanCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ModelZanCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ModelZanCount)
        microservice.protoc.zan.grpc.Zan.ModelZanCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZanCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZanCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                microservice.protoc.zan.grpc.Zan.ModelZanCount.class, microservice.protoc.zan.grpc.Zan.ModelZanCount.Builder.class);
      }

      // Construct using microservice.protoc.zan.grpc.Zan.ModelZanCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        appId_ = 0;

        thirdId_ = 0;

        realCount_ = 0;

        showCount_ = 0;

        createdAt_ = 0;

        updatedAt_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZanCount_descriptor;
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZanCount getDefaultInstanceForType() {
        return microservice.protoc.zan.grpc.Zan.ModelZanCount.getDefaultInstance();
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZanCount build() {
        microservice.protoc.zan.grpc.Zan.ModelZanCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZanCount buildPartial() {
        microservice.protoc.zan.grpc.Zan.ModelZanCount result = new microservice.protoc.zan.grpc.Zan.ModelZanCount(this);
        result.id_ = id_;
        result.appId_ = appId_;
        result.thirdId_ = thirdId_;
        result.realCount_ = realCount_;
        result.showCount_ = showCount_;
        result.createdAt_ = createdAt_;
        result.updatedAt_ = updatedAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof microservice.protoc.zan.grpc.Zan.ModelZanCount) {
          return mergeFrom((microservice.protoc.zan.grpc.Zan.ModelZanCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(microservice.protoc.zan.grpc.Zan.ModelZanCount other) {
        if (other == microservice.protoc.zan.grpc.Zan.ModelZanCount.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getThirdId() != 0) {
          setThirdId(other.getThirdId());
        }
        if (other.getRealCount() != 0) {
          setRealCount(other.getRealCount());
        }
        if (other.getShowCount() != 0) {
          setShowCount(other.getShowCount());
        }
        if (other.getCreatedAt() != 0) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.getUpdatedAt() != 0) {
          setUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        microservice.protoc.zan.grpc.Zan.ModelZanCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (microservice.protoc.zan.grpc.Zan.ModelZanCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 2;</code>
       */
      public Builder setAppId(int value) {
        
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 2;</code>
       */
      public Builder clearAppId() {
        
        appId_ = 0;
        onChanged();
        return this;
      }

      private int thirdId_ ;
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 3;</code>
       */
      public int getThirdId() {
        return thirdId_;
      }
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 3;</code>
       */
      public Builder setThirdId(int value) {
        
        thirdId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 3;</code>
       */
      public Builder clearThirdId() {
        
        thirdId_ = 0;
        onChanged();
        return this;
      }

      private int realCount_ ;
      /**
       * <pre>
       * 真实点赞数
       * </pre>
       *
       * <code>int32 real_count = 4;</code>
       */
      public int getRealCount() {
        return realCount_;
      }
      /**
       * <pre>
       * 真实点赞数
       * </pre>
       *
       * <code>int32 real_count = 4;</code>
       */
      public Builder setRealCount(int value) {
        
        realCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 真实点赞数
       * </pre>
       *
       * <code>int32 real_count = 4;</code>
       */
      public Builder clearRealCount() {
        
        realCount_ = 0;
        onChanged();
        return this;
      }

      private int showCount_ ;
      /**
       * <pre>
       * 展示点赞数
       * </pre>
       *
       * <code>int32 show_count = 5;</code>
       */
      public int getShowCount() {
        return showCount_;
      }
      /**
       * <pre>
       * 展示点赞数
       * </pre>
       *
       * <code>int32 show_count = 5;</code>
       */
      public Builder setShowCount(int value) {
        
        showCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 展示点赞数
       * </pre>
       *
       * <code>int32 show_count = 5;</code>
       */
      public Builder clearShowCount() {
        
        showCount_ = 0;
        onChanged();
        return this;
      }

      private int createdAt_ ;
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public int getCreatedAt() {
        return createdAt_;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public Builder setCreatedAt(int value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0;
        onChanged();
        return this;
      }

      private int updatedAt_ ;
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public int getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public Builder setUpdatedAt(int value) {
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ModelZanCount)
    }

    // @@protoc_insertion_point(class_scope:ModelZanCount)
    private static final microservice.protoc.zan.grpc.Zan.ModelZanCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new microservice.protoc.zan.grpc.Zan.ModelZanCount();
    }

    public static microservice.protoc.zan.grpc.Zan.ModelZanCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModelZanCount>
        PARSER = new com.google.protobuf.AbstractParser<ModelZanCount>() {
      @java.lang.Override
      public ModelZanCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelZanCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModelZanCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModelZanCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public microservice.protoc.zan.grpc.Zan.ModelZanCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModelZanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ModelZan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 收藏内容ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int32 user_id = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     * APP内容类型
     * </pre>
     *
     * <code>int32 app_id = 3;</code>
     */
    int getAppId();

    /**
     * <pre>
     * APP内容ID
     * </pre>
     *
     * <code>int32 third_id = 4;</code>
     */
    int getThirdId();

    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>int32 source = 5;</code>
     */
    int getSource();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int32 created_at = 6;</code>
     */
    int getCreatedAt();

    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>int32 updated_at = 7;</code>
     */
    int getUpdatedAt();
  }
  /**
   * Protobuf type {@code ModelZan}
   */
  public  static final class ModelZan extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ModelZan)
      ModelZanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ModelZan.newBuilder() to construct.
    private ModelZan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModelZan() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ModelZan();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ModelZan(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 24: {

              appId_ = input.readInt32();
              break;
            }
            case 32: {

              thirdId_ = input.readInt32();
              break;
            }
            case 40: {

              source_ = input.readInt32();
              break;
            }
            case 48: {

              createdAt_ = input.readInt32();
              break;
            }
            case 56: {

              updatedAt_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return microservice.protoc.zan.grpc.Zan.internal_static_ModelZan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return microservice.protoc.zan.grpc.Zan.internal_static_ModelZan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              microservice.protoc.zan.grpc.Zan.ModelZan.class, microservice.protoc.zan.grpc.Zan.ModelZan.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 收藏内容ID
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int32 user_id = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int APP_ID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <pre>
     * APP内容类型
     * </pre>
     *
     * <code>int32 app_id = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    public static final int THIRD_ID_FIELD_NUMBER = 4;
    private int thirdId_;
    /**
     * <pre>
     * APP内容ID
     * </pre>
     *
     * <code>int32 third_id = 4;</code>
     */
    public int getThirdId() {
      return thirdId_;
    }

    public static final int SOURCE_FIELD_NUMBER = 5;
    private int source_;
    /**
     * <pre>
     * 来源
     * </pre>
     *
     * <code>int32 source = 5;</code>
     */
    public int getSource() {
      return source_;
    }

    public static final int CREATED_AT_FIELD_NUMBER = 6;
    private int createdAt_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int32 created_at = 6;</code>
     */
    public int getCreatedAt() {
      return createdAt_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 7;
    private int updatedAt_;
    /**
     * <pre>
     * 更新时间
     * </pre>
     *
     * <code>int32 updated_at = 7;</code>
     */
    public int getUpdatedAt() {
      return updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (appId_ != 0) {
        output.writeInt32(3, appId_);
      }
      if (thirdId_ != 0) {
        output.writeInt32(4, thirdId_);
      }
      if (source_ != 0) {
        output.writeInt32(5, source_);
      }
      if (createdAt_ != 0) {
        output.writeInt32(6, createdAt_);
      }
      if (updatedAt_ != 0) {
        output.writeInt32(7, updatedAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (appId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, appId_);
      }
      if (thirdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, thirdId_);
      }
      if (source_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, source_);
      }
      if (createdAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, createdAt_);
      }
      if (updatedAt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, updatedAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof microservice.protoc.zan.grpc.Zan.ModelZan)) {
        return super.equals(obj);
      }
      microservice.protoc.zan.grpc.Zan.ModelZan other = (microservice.protoc.zan.grpc.Zan.ModelZan) obj;

      if (getId()
          != other.getId()) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getAppId()
          != other.getAppId()) return false;
      if (getThirdId()
          != other.getThirdId()) return false;
      if (getSource()
          != other.getSource()) return false;
      if (getCreatedAt()
          != other.getCreatedAt()) return false;
      if (getUpdatedAt()
          != other.getUpdatedAt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId();
      hash = (37 * hash) + THIRD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getThirdId();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource();
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt();
      hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static microservice.protoc.zan.grpc.Zan.ModelZan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(microservice.protoc.zan.grpc.Zan.ModelZan prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ModelZan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ModelZan)
        microservice.protoc.zan.grpc.Zan.ModelZanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZan_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                microservice.protoc.zan.grpc.Zan.ModelZan.class, microservice.protoc.zan.grpc.Zan.ModelZan.Builder.class);
      }

      // Construct using microservice.protoc.zan.grpc.Zan.ModelZan.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        userId_ = 0;

        appId_ = 0;

        thirdId_ = 0;

        source_ = 0;

        createdAt_ = 0;

        updatedAt_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return microservice.protoc.zan.grpc.Zan.internal_static_ModelZan_descriptor;
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZan getDefaultInstanceForType() {
        return microservice.protoc.zan.grpc.Zan.ModelZan.getDefaultInstance();
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZan build() {
        microservice.protoc.zan.grpc.Zan.ModelZan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public microservice.protoc.zan.grpc.Zan.ModelZan buildPartial() {
        microservice.protoc.zan.grpc.Zan.ModelZan result = new microservice.protoc.zan.grpc.Zan.ModelZan(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.appId_ = appId_;
        result.thirdId_ = thirdId_;
        result.source_ = source_;
        result.createdAt_ = createdAt_;
        result.updatedAt_ = updatedAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof microservice.protoc.zan.grpc.Zan.ModelZan) {
          return mergeFrom((microservice.protoc.zan.grpc.Zan.ModelZan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(microservice.protoc.zan.grpc.Zan.ModelZan other) {
        if (other == microservice.protoc.zan.grpc.Zan.ModelZan.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getAppId() != 0) {
          setAppId(other.getAppId());
        }
        if (other.getThirdId() != 0) {
          setThirdId(other.getThirdId());
        }
        if (other.getSource() != 0) {
          setSource(other.getSource());
        }
        if (other.getCreatedAt() != 0) {
          setCreatedAt(other.getCreatedAt());
        }
        if (other.getUpdatedAt() != 0) {
          setUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        microservice.protoc.zan.grpc.Zan.ModelZan parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (microservice.protoc.zan.grpc.Zan.ModelZan) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 收藏内容ID
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int32 user_id = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int32 user_id = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户ID
       * </pre>
       *
       * <code>int32 user_id = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private int appId_ ;
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 3;</code>
       */
      public Builder setAppId(int value) {
        
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APP内容类型
       * </pre>
       *
       * <code>int32 app_id = 3;</code>
       */
      public Builder clearAppId() {
        
        appId_ = 0;
        onChanged();
        return this;
      }

      private int thirdId_ ;
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 4;</code>
       */
      public int getThirdId() {
        return thirdId_;
      }
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 4;</code>
       */
      public Builder setThirdId(int value) {
        
        thirdId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * APP内容ID
       * </pre>
       *
       * <code>int32 third_id = 4;</code>
       */
      public Builder clearThirdId() {
        
        thirdId_ = 0;
        onChanged();
        return this;
      }

      private int source_ ;
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       */
      public int getSource() {
        return source_;
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       */
      public Builder setSource(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 来源
       * </pre>
       *
       * <code>int32 source = 5;</code>
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private int createdAt_ ;
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public int getCreatedAt() {
        return createdAt_;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public Builder setCreatedAt(int value) {
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int32 created_at = 6;</code>
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = 0;
        onChanged();
        return this;
      }

      private int updatedAt_ ;
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public int getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public Builder setUpdatedAt(int value) {
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新时间
       * </pre>
       *
       * <code>int32 updated_at = 7;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ModelZan)
    }

    // @@protoc_insertion_point(class_scope:ModelZan)
    private static final microservice.protoc.zan.grpc.Zan.ModelZan DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new microservice.protoc.zan.grpc.Zan.ModelZan();
    }

    public static microservice.protoc.zan.grpc.Zan.ModelZan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModelZan>
        PARSER = new com.google.protobuf.AbstractParser<ModelZan>() {
      @java.lang.Override
      public ModelZan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ModelZan(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModelZan> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModelZan> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public microservice.protoc.zan.grpc.Zan.ModelZan getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModelZanCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModelZanCount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ModelZan_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ModelZan_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tzan.proto\"\215\001\n\rModelZanCount\022\n\n\002id\030\001 \001(" +
      "\005\022\016\n\006app_id\030\002 \001(\005\022\020\n\010third_id\030\003 \001(\005\022\022\n\nr" +
      "eal_count\030\004 \001(\005\022\022\n\nshow_count\030\005 \001(\005\022\022\n\nc" +
      "reated_at\030\006 \001(\005\022\022\n\nupdated_at\030\007 \001(\005\"\201\001\n\010" +
      "ModelZan\022\n\n\002id\030\001 \001(\005\022\017\n\007user_id\030\002 \001(\005\022\016\n" +
      "\006app_id\030\003 \001(\005\022\020\n\010third_id\030\004 \001(\005\022\016\n\006sourc" +
      "e\030\005 \001(\005\022\022\n\ncreated_at\030\006 \001(\005\022\022\n\nupdated_a" +
      "t\030\007 \001(\005B\036\n\034microservice.protoc.zan.grpcb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ModelZanCount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ModelZanCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModelZanCount_descriptor,
        new java.lang.String[] { "Id", "AppId", "ThirdId", "RealCount", "ShowCount", "CreatedAt", "UpdatedAt", });
    internal_static_ModelZan_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ModelZan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ModelZan_descriptor,
        new java.lang.String[] { "Id", "UserId", "AppId", "ThirdId", "Source", "CreatedAt", "UpdatedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
